[package]
name = "radius-circuit"
version = "0.1.0"
edition = "2021"

[dependencies]
ff = "0.13.0"
nova = { git = "https://github.com/wyattbenno777/arecibo", branch = "feat/onchain-verifier", package = "arecibo" }
serde_json = "1.0.133"
halo2curves = { git = "https://github.com/ICME-Lab/halo2curves", branch = "main", features = ["bits", "derive_serde"] }
rand = "0.8.5"